"""Initial Migration

Revision ID: 1060ee5817c7
Revises: eb9d235e3e38
Create Date: 2019-03-04 16:45:11.772516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1060ee5817c7'
down_revision = 'eb9d235e3e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('subscribers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('subscribers', 'username')
    # ### end Alembic commands ###
