"""add class of delete

Revision ID: f83defd9c5ed
Revises: 1060ee5817c7
Create Date: 2019-03-04 17:50:54.573744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83defd9c5ed'
down_revision = '1060ee5817c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
